openapi: '3.0.2'
info:
  title: snapshots
  version: '1.0'
paths:
  /snapshots:
    get:
      description: 'Returns the most recent plant snapshot'
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Snapshot'
    post:
      description: 'Stores an snapshot'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Snapshot'
      parameters: []
      responses:
        '200':
          description: OK

components:
  schemas:
    Snapshot:
      type: object
      properties:
        user_id:
          type: string
          format: uuid
        plant_id:
          type: string
          format: uuid
        timestamp:
          description: The timestamp at which the snapshot was captured.
          type: string
          format: date-time
        health_properties:
          $ref: '#/components/schemas/HealthProperties'

    HealthProperties:
      description: Raw metrics and user-friendly interpretation of the plant's health properties
      type: array
      items:
        $ref: '#/components/schemas/HealthProperty'

    HealthProperty:
      description: The health property of a plant
      type: object
      properties:
        metric:
          type: string
        level:
          type: number
          format: float
        unit:
          type: string
        interpretation:
          $ref: '#/components/schemas/Interpretation'

    Interpretation:
      description: PC's interpretation of the given healthProperty
      type: string
      enum: [GOOD, OKAY, CRITICAL]