openapi: '3.0.2'
info:
  title: snapshots
  version: '1.0'
paths:
  /snapshots:
    get:
      description: 'Returns the most recent plant snapshot'
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Snapshot'
    post:
      description: 'Stores an snapshot'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Snapshot'
      parameters: []
      responses:
        '200':
          description: OK

components:
  schemas:
    Snapshot:
      type: object
      properties:
        user_id:
          $ref: '#/components/schemas/Id'
        plant_id:
          $ref: '#/components/schemas/Id'
        timestamp:
          description: The timestamp at which the snapshot was captured.
          $ref: '#/components/schemas/Timestamp'
        health_properties:
          $ref: '#/components/schemas/HealthProperties'

    HealthProperties:
      description: Raw metrics and user-friendly interpretation of the plant's health properties. Formatted as a map with the metric as a key
      type: object
      additionalProperties:
        $ref: '#/components/schemas/HealthProperty'

    HealthProperty:
      description: The health property of a plant.
      type: object
      properties:
        level:
          type: number
          format: float
        unit:
          type: string
        interpretation:
          $ref: '#/components/schemas/Interpretation'

    Interpretation:
      description: PC's interpretation of the given healthProperty
      type: string
      enum: [GOOD, OKAY, CRITICAL]

    Id:
      type: string
      format: uuid

    Timestamp: 
      type: string
      format: date-time